/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pacoteprincipal;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Iksortso K2
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    MaskFormatter mfdata;
    Pilha pilha = new Pilha(5);
    Pilha pilhaDesempilha = new Pilha(5);

    public FormularioPrincipal() {

        try {
            mfdata = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            System.out.println("Ocorreu um erro na criação da máscara");
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_tempo = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        lbl_tempo = new javax.swing.JLabel();
        btn_empilhar = new javax.swing.JButton();
        btn_desempilhar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        txt_data = new javax.swing.JFormattedTextField(mfdata);
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_area1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area2 = new javax.swing.JTextArea();
        lbl_aviso = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Pilha de Recordes ");

        lbl_nome.setText("Digite o nome:");

        lbl_data.setText("Digite a data:");

        lbl_tempo.setText("Tempo:");

        btn_empilhar.setText("Empilhar");
        btn_empilhar.setToolTipText("");
        btn_empilhar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_empilharMouseClicked(evt);
            }
        });

        btn_desempilhar.setText("Desempilhar");
        btn_desempilhar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_desempilharMouseClicked(evt);
            }
        });

        btn_limpar.setText("Limpar");
        btn_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_limparMouseClicked(evt);
            }
        });

        txt_area1.setColumns(20);
        txt_area1.setRows(5);
        jScrollPane2.setViewportView(txt_area1);

        txt_area2.setColumns(20);
        txt_area2.setRows(5);
        jScrollPane1.setViewportView(txt_area2);

        lbl_aviso.setText("-");

        jLabel2.setText("Desenvolvido por: Línicker Ostroski Mota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_data)
                            .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tempo)
                            .addComponent(txt_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(31, 31, 31)
                                .addComponent(lbl_aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_limpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_desempilhar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_empilhar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lbl_aviso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(lbl_data)
                    .addComponent(lbl_tempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_desempilhar)
                    .addComponent(btn_limpar)
                    .addComponent(btn_empilhar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("lbl_titulo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_empilharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_empilharMouseClicked

        //Tentativa de pegar os valores dos elementos e passar para o Recorde
        Recorde recorde = new Recorde();

        try {
            String nome = txt_nome.getText();
            String data = txt_data.getText();
            double tempo = Double.parseDouble(txt_tempo.getText());

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date dataFormatada = formato.parse(data);

            recorde.setNome(nome);
            recorde.setDataRecorde(dataFormatada);
            recorde.setTempo(tempo);

            if (!pilha.isFull()) {
                pilha.push(recorde);
                lbl_aviso.setText("");
            } else {
                lbl_aviso.setText("Stack OverFlow!");
            }

            txt_area1.setText(pilha.toString());
            System.out.println("Sucesso!");

        } catch (ParseException ex) {

            System.out.println("Erro ao pegar os valores");

        }

        txt_nome.setText("");
        txt_data.setText("");
        txt_tempo.setText("");
        txt_nome.requestFocus();
    }//GEN-LAST:event_btn_empilharMouseClicked

    private void btn_desempilharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_desempilharMouseClicked

        if (!pilhaDesempilha.isFull()) {
            pilhaDesempilha.push(pilha.peek());
            lbl_aviso.setText("");
        } else {
            lbl_aviso.setText("Stack OverFlow! Pilha II");
        }

        txt_area2.setText(pilhaDesempilha.toString());

        pilha.pop();

        System.out.println("Desempilhando");

        txt_area1.setText(pilha.toString());

        txt_nome.setText("");
        txt_data.setText("");
        txt_tempo.setText("");
        txt_nome.requestFocus();
    }//GEN-LAST:event_btn_desempilharMouseClicked

    private void btn_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparMouseClicked

        // Desempilhando tudo
        while (!pilha.isEmpty()) {
            pilha.pop();
        }
        txt_area1.setText(pilha.toString());
        
        while (pilhaDesempilha.isEmpty() == false) {
            pilhaDesempilha.pop();
        }
        txt_area2.setText(pilhaDesempilha.toString());

        txt_nome.setText("");
        txt_data.setText("");
        txt_tempo.setText("");
        txt_nome.requestFocus();
    }//GEN-LAST:event_btn_limparMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_desempilhar;
    private javax.swing.JButton btn_empilhar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_aviso;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_tempo;
    private javax.swing.JTextArea txt_area1;
    private javax.swing.JTextArea txt_area2;
    private javax.swing.JFormattedTextField txt_data;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_tempo;
    // End of variables declaration//GEN-END:variables
}
